apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-store
  namespace: dapr-example
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.dapr-example.svc.cluster.local:6379
  - name: redisPassword
    value: ZQiYR9ATxM