apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dapr-example
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.dapr-example.svc.cluster.local:6379
  - name: redisPassword
    value: ZQiYR9ATxM
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  route: /listen
  pubsubname: pubsub
scopes:
- order-service