apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: dapr-example
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4K
  password: ZW5naW4K
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: dapr-example #for non-default namespace
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-example
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: "basic-auth"